// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHT-2u3zIFKJID1AsSRK9Zb5_EaE_VSyU',
    appId: '1:448521423728:web:dcccc60a05a216af05ddb5',
    messagingSenderId: '448521423728',
    projectId: 'cass-b77b0',
    authDomain: 'cass-b77b0.firebaseapp.com',
    storageBucket: 'cass-b77b0.firebasestorage.app',
    measurementId: 'G-MZ4JTQLMVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_B1HxabzID42_-wBDWCBlOW32hTNcxKQ',
    appId: '1:448521423728:android:f3414f814cc4604c05ddb5',
    messagingSenderId: '448521423728',
    projectId: 'cass-b77b0',
    storageBucket: 'cass-b77b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQmFLKJsgXyAHYAelMESRapVjozXDmom0',
    appId: '1:448521423728:ios:3262a1d3f3efe54a05ddb5',
    messagingSenderId: '448521423728',
    projectId: 'cass-b77b0',
    storageBucket: 'cass-b77b0.firebasestorage.app',
    iosBundleId: 'com.example.cass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQmFLKJsgXyAHYAelMESRapVjozXDmom0',
    appId: '1:448521423728:ios:3262a1d3f3efe54a05ddb5',
    messagingSenderId: '448521423728',
    projectId: 'cass-b77b0',
    storageBucket: 'cass-b77b0.firebasestorage.app',
    iosBundleId: 'com.example.cass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHT-2u3zIFKJID1AsSRK9Zb5_EaE_VSyU',
    appId: '1:448521423728:web:78dd2c3a3b3efe6105ddb5',
    messagingSenderId: '448521423728',
    projectId: 'cass-b77b0',
    authDomain: 'cass-b77b0.firebaseapp.com',
    storageBucket: 'cass-b77b0.firebasestorage.app',
    measurementId: 'G-3Y9647H7L9',
  );
}
